### ISSUE TITLE
misguiding install instructions

### ISSUE THREAD

**Issue by spescina** [schuppo/PasswordStrengthPackage#17]
do not suggest to use `composer update` in the install instructions. the only way to install a package should be `composer require`

**Comment by schuppo** [comment]
I leave it up to the user in the install instructions and I think that is okay as long as changing `composer.json` manually isn't considered a bad habit (and as far as I know it isn't).

**Comment by spescina** [comment]
A `composer update` will trigger a forced update of all dependencies. A fresh install of a new package should not change the state of the application.

**Comment by schuppo** [comment]
Good argument. I will change the install instructions

**Comment by schuppo** [comment]
Done. Thanks for hint and explanation.
