### ISSUE TITLE
'confirmed' not working

### ISSUE THREAD

**Issue by Mapamatician** [schuppo/PasswordStrengthPackage#25]
Hey guys,
Thanks for the awesome plugin.

However since adding it, the 'confirmed' password validator is no longer working for me on Laravel 5.3
 
This does not work
```
    public function register(Request $request)
    {
        $this->validate($request, [
'password' => 'required|confirmed|min:6|case_diff|numbers|letters|symbols
```

however, this does.
```
    public function register(Request $request)
    {
        $this->validate($request, [
'password' => 'required|confirmed'
```

How can I take advantage of your plugin with confirmed?

and yes my div's are named _confirmation

                    
                    <label for="password">Password</label>
                    <div class="input-group">
                        <input id="password" name="password" type="password" class="form-control" placeholder="Create a strong password" aria-describedby="sizing-addon2" />
                    </div>

                    
                    <label for="password_confirmation">Confirm Password</label>
                    <div class="input-group">
                        <input name="password_confirmation" type="password" class="form-control" placeholder="Repeat your strong password" aria-describedby="sizing-addon2"  />
                    </div>

Hope you can help-
Thanks.

**Comment by Mapamatician** [comment]
I removed case_diff|numbers|letters|symbols'
made a git commit & push to live server
added it again, git push
Works now. Not sure what happened

**Comment by schuppo** [comment]
So I can close this issue?
