### ISSUE TITLE
Validation rules are displayed one at a time

### ISSUE THREAD

**Issue by tommym9** [schuppo/PasswordStrengthPackage#30]
Hi,

Firstly thanks for this package, it really helped me out.

One quite serious UX issue is that it will show validation errors one at a time. For example:

- A user enters a password with no caps and gets an error about no caps
- A user then enters a password with caps and gets an error about no numbers
- A user then enters a password with caps and numbers and gets an error about no symbols

This is quite frustrating for users, I'm not sure what the solution is (if there is one) but I wanted to flag it up.

Cheers

Tom

**Comment by schuppo** [comment]
Hi,

the validator should detect three validation errors at the user's first try. Probably you are showing only the first error message.

> public function test_case_diff_numbers_symbols()
>     {
>         $validation = $this->validation->make(
>             array( 'password' => 'tt' ),
>             array( 'password' => 'case_diff|numbers|symbols' )
>         );
>         $this->assertCount(3, $validation->errors());
>     }

See "Retrieving All Error Messages For A Field" @ https://laravel.com/docs/5.5/validation#working-with-error-messages. 

Does this help?
