### ISSUE TITLE
Laravel 6 compatibility?

### ISSUE THREAD

**Issue by snipe** [schuppo/PasswordStrengthPackage#38]
Hi there - any chance there will be a release that works with Laravel 6?

Thanks so much!

**Comment by piep14** [comment]
@schuppo  Can you support Laravel 6 ? Thank you !

**Comment by schuppo** [comment]
done: 0ae24ba87a81ed9ed1ff4368a31af5a1850566a8

**Comment by dododedodonl** [comment]
@schuppo Could you also tag the commit with a new version so packagist sees the changes?

**Comment by schuppo** [comment]
done. the latest release is tagged v1.12: https://github.com/schuppo/PasswordStrengthPackage/releases/tag/v1.12
