### ISSUE TITLE
Laravel 5.6.39: In PasswordStrengthServiceProvider.php line 38: Class 'Str' not found 

### ISSUE THREAD

**Issue by tjhunkin** [schuppo/PasswordStrengthPackage#40]
I ran composer update and got this error:

Laravel 5.6.39: In PasswordStrengthServiceProvider.php line 38: Class 'Str' not found

**Comment by tjhunkin** [comment]
should be 
use Illuminate\Support\Str;
$snakeCasedRule = Str::snake($rule);

**Comment by schuppo** [comment]
@tjhunkin does the last release (https://github.com/schuppo/PasswordStrengthPackage/releases/tag/v1.13) solve this issue?

**Comment by tjhunkin** [comment]
changed composer to "schuppo/password-strength": "~1.13",

ran composer update

Package operations: 0 installs, 1 update, 0 removals
  - Removing schuppo/password-strength (v1.12)
  - Installing schuppo/password-strength (1.x-dev 70ee699)

In PasswordStrengthServiceProvider.php line 38:

  Class 'Str' not found

**Comment by jelleroorda** [comment]
@tjhunkin To remedy this for the time being you can add an alias to your `config/app.php`. Add the following key value pair to your 'aliases' key: `'Str'       => Illuminate\Support\Str::class,
`. Even though this is indeed a bug in the package, you can 'fix it' like this temporarily.

**Comment by SuperlativeEntity** [comment]
Cool, thanks.
