### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by Zahnerweb** [schuppo/PasswordStrengthPackage#41]
Hey!

Are there any plans to support Laravel 7? I would be happy to submit a PR if needed.

**Comment by clnt** [comment]
@Zahnerweb @schuppo 

Pull request submitted, please tag 2.0.0 :) https://github.com/schuppo/PasswordStrengthPackage/pull/42

**Comment by clnt** [comment]
@Zahnerweb PR has now been merged, however I cannot see a tag for the release. You could pull down master by changing the version constraint in your `composer.json` file to `dev-master` which will include the changes.

@schuppo Could we create a 2.x branch off master and release a 2.0.0 tag please? :) Now the readme has been updated this will prevent confusion and potentially more issues. Thanks!

Can get this issue closed off and the open PR closed off too then to avoid any confusion.

**Comment by Dalabad** [comment]
> @schuppo Could we create a 2.x branch off master and release a 2.0.0 tag please? :) Now the readme has been updated this will prevent confusion and potentially more issues. Thanks!

I agree, the release is created but not tagged with 2.0 while the readme already indicates that this exists. Please create the correct tag and close this issue

**Comment by schuppo** [comment]
done
