### ISSUE TITLE
Add support for Laravel 10

### ISSUE THREAD

**Issue by donnyxray** [schuppo/PasswordStrengthPackage#58]
Please add support for Laravel 10.

**Comment by volkeransmann** [comment]
Yes please!

**Comment by hcaz** [comment]
You can see the automated pull request from shift here #57 which tells you how you can use it in the meantime.

@schuppo it would be good to get that PR merged.

**Comment by schuppo** [comment]
Done in the latest release: 
https://github.com/schuppo/PasswordStrengthPackage/releases/tag/v2.7

Thanks for your contribution!
