### ISSUE TITLE
Service provider inverted slashes.

### ISSUE THREAD

**Issue by vpakg** [schuppo/PasswordStrengthPackage#6]
Hey man, great work. But I think your service provider have inverted slashes. 

it should be ` 'Schuppo\PasswordStrength\PasswordStrengthServiceProvider',` instead of  `'Schuppo/PasswordStrength/PasswordStrengthServiceProvider',` no?

**Comment by vpakg** [comment]
@schuppo is there a reason for closing this issue? Just wondering.

**Comment by schuppo** [comment]
@vpakg Did I forgot to fix it anywhere else? I thought your post related only to the readme file. Am I wrong?
Thanks for the hint btw.

**Comment by vpakg** [comment]
@schuppo oh nevermind. I must be going crazy. Again, great work.

**Comment by schuppo** [comment]
Thanks!
