### ISSUE TITLE
Proposal for "fr" language translation

### ISSUE THREAD

**Issue by paguemaou** [schuppo/PasswordStrengthPackage#7]
Here is my proposal for a "fr" translation :

return [ 
             "letters" => "Le champ :attribute doit comprendre au moins une lettre.", 
             "case_diff" => "Le champ :attribute doit comprendre des lettres minuscules et majuscules.", 
             "numbers" => "Le champ :attribute doit comprendre au moins un nombre.", 
             "symbols" => "Le champ:attribute doit comprendre au moins un symbole (#,@,$, etc.)." 
 ];

**Comment by schuppo** [comment]
@paguemaou Thanks for your contribution! I have added your translation suggestion to the repo.
